"""01-create-tables

Revision ID: aa15f1e246a7
Revises: 
Create Date: 2024-04-23 18:24:37.897306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa15f1e246a7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    op.create_table(
        'tracks',
        sa.Column('id', sa.Integer, primary_key=True, autoincrement=True),
        sa.Column('item_name', sa.String),
        sa.Column('image_url', sa.String),
    )

    op.create_table(
        'categories',
        sa.Column('id', sa.Integer, primary_key=True, autoincrement=True),
        sa.Column('cat_name', sa.String)
    )

    op.create_table(
        'tracks_sort',
        sa.Column('track_id', sa.Integer, sa.ForeignKey('tracks.id')),
        sa.Column('categories_id', sa.Integer, sa.ForeignKey('categories.id'))
    )

    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
