"""02-add-data

Revision ID: 601e248428cb
Revises: 3f6a1736dbe3
Create Date: 2024-04-23 17:59:21.310931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = '601e248428cb'
down_revision: Union[str, None] = 'aa15f1e246a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
   
    category_list_table = sa.Table(
        'categories',
        sa.MetaData(),
        sa.Column('id', sa.Integer),
        sa.Column('cat_name', sa.String)
    )
    
    
    op.bulk_insert(category_list_table, [
        {'cat_name': 'Gabona félék'},
        {'cat_name': 'Gyümölcs'},
        {'cat_name': 'Hús és hal'},
        {'cat_name': 'Hüvelyesek, magvak'},
        {'cat_name': 'Játék'},
        {'cat_name': 'Tejtermékek'},
        {'cat_name': 'Tojás'},
        {'cat_name': 'Zöldségek'},
        {'cat_name': 'Egyéb'}
    ])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ##
    pass